import { DevtoolsProvider } from '@providers/devtools';
import { GitHubBanner, Refine } from '@refinedev/core';
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar';
import routerProvider from '@refinedev/nextjs-router';
import { Metadata } from 'next';
import React, { Suspense } from 'react';

import { dataProvider } from '@providers/data-provider';
import '@styles/global.css';
import { schedulerDataProvider } from '@providers/scheduler-data-provider';

export const metadata: Metadata = {
    title       : 'Refine',
    description : 'Generated by create refine app',
    icons       : {
        icon : '/favicon.ico'
    }
};

export default function RootLayout({
    children
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Suspense>
                    <GitHubBanner />
                    <RefineKbarProvider>
                        <DevtoolsProvider>
                            <Refine
                                routerProvider={routerProvider}
                                dataProvider={{
                                // `default` is required to determine the default data provider
                                    default   : dataProvider,
                                    scheduler : schedulerDataProvider
                                }}
                                resources={[
                                    {
                                        name   : 'blog_posts',
                                        list   : '/blog-posts',
                                        create : '/blog-posts/create',
                                        edit   : '/blog-posts/edit/:id',
                                        show   : '/blog-posts/show/:id',
                                        meta   : {
                                            canDelete : true
                                        }
                                    },
                                    {
                                        name   : 'categories',
                                        list   : '/categories',
                                        create : '/categories/create',
                                        edit   : '/categories/edit/:id',
                                        show   : '/categories/show/:id',
                                        meta   : {
                                            canDelete : true
                                        }
                                    },
                                    {
                                        name : 'scheduler',
                                        list : '/scheduler',
                                        meta : {
                                            dataProviderName : 'scheduler'
                                        }
                                    },
                                    {
                                        name : 'events',
                                        list : '/events',
                                        meta : {
                                            dataProviderName : 'scheduler'
                                        }
                                    }
                                ]}
                                options={{
                                    syncWithLocation       : true,
                                    warnWhenUnsavedChanges : true,
                                    useNewQueryKeys        : true,
                                    projectId              : '29JpC5-mXjybd-1RmKPt'
                                }}
                            >
                                {children}
                                <RefineKbar />
                            </Refine>
                        </DevtoolsProvider>
                    </RefineKbarProvider>
                </Suspense>
            </body>
        </html>
    );
}
